var g=angular.module('grade',[]);
g.config(["$routeProvider",function($routeProvider){
    $routeProvider.when('/old_ListTrack',{//我的中心
        templateUrl:"tpl/old/old_ListTrack.html"
    })
    .when('/old_ListAddTalkNotice',{
        templateUrl:"tpl/old/old_ListAddTalkNotice.html"
    })
    .when('/old_ListAlbum',{
        templateUrl:"tpl/old/old_ListAlbum.html"
    })
    .when('/EditorAlbum',{
        templateUrl:"tpl/old/EditorAlbum.html"
    })
    .when('/Forum',{
        templateUrl:"tpl/old/Forum.html"
    })
    .when('/addForum',{
        templateUrl:"tpl/old/addForum.html"
    })
    .when('/Curriculum',{
        templateUrl:"tpl/old/Curriculum.html"
    })
    .when('/open_class',{
        templateUrl:"tpl/grade/open_class.html"
    })
    .when('/select_class',{
        templateUrl:"tpl/grade/select_class.html"
    })
    .when('/push_class',{
        templateUrl:"tpl/grade/push_class.html"
    })
    .when('/class_management',{
        templateUrl:"tpl/grade/class_management.html"
    })
    .when('/class_list',{
        templateUrl:"tpl/grade/class_list.html"
    })
    .when('/add_teacher',{
        templateUrl:"tpl/grade/add_teacher.html"
    })
    .when('/shezhi',{
        templateUrl:"tpl/grade/shezhi.html"
    })
    .when('/guanli',{
        templateUrl:"tpl/grade/guanli.html"
    })
    .when('/upgrade_class',{
        templateUrl:"tpl/grade/upgrade_class.html"
    })
    .when('/transfer_class',{
        templateUrl:"tpl/grade/transfer_class.html"
    });
}]);